### ISSUE TITLE
PATCH should be able to update expires time

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#100]

**Comment by KieranP** [comment]
Agreed. I handle GBs of uploads an hour, and I'd like to set a 30 minute expiry, but if the file is still being uploaded, obviously don't want it deleting what has been done so far. The patch request is the best place to update the expire time. I imagine this could be done fairly easily in the server implementations, and be backward compatible with current protocol by being an option in the server (config.update_expire_on_patch = true).

**Comment by Acconut** [comment]
The protocol does already allow this. Quoting from the specification:

> This [Upload-Expires] header MUST be included in every PATCH response if the upload is going to expire. If the expiration is known at the creation, the Upload-Expires header MUST be included in the response to the initial POST request. **Its value MAY change over time.**

Or did you have something different in mind?

**Comment by KieranP** [comment]
@Acconut The spec may allow for it, but if it doesn't specifically state it, server side implementations probably won't add it.

So I would recommend adding this under the "Requests > PATCH" section of the spec:

"The Server SHOULD update a files Upload-Expires header with each PATCH request to prevent file expiration while the file is still being actively uploaded."

And this under the Extensions > Expiration section:

"The Server SHOULD NOT expire any files that are being actively uploaded. This can be achieved by updating a files Upload-Expires header with each PATCH request."

**Comment by Acconut** [comment]
@KieranP Good idea! Would you mind opening a pull request for this change? However, I would add both paragraphs to the section about the Expiration extension, as this is the scope in which the Upload-Expires header is defined.

**Comment by KieranP** [comment]
@Acconut Thank you. I have opened a PR here: https://github.com/tus/tus-resumable-upload-protocol/compare/master...KieranP:patch-1
