### ISSUE TITLE
PATCH should contain correct offset if mismatching

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#101]
This way it is possible to perform an upload without doing a HEAD call first to find the upload-offset.

**Comment by Acconut** [comment]
Already required. Quoting the specification:

> The Server MUST acknowledge successful PATCH requests with the 204 No Content status. **It MUST include the Upload-Offset header containing the new offset.** The new offset MUST be the sum of the offset before the PATCH request and the number of bytes received and processed or stored during the current PATCH request.

**Comment by Acconut** [comment]
Good idea :+1:

**Comment by ronag** [comment]
@Acconut: With this `HEAD` would no longer be required and could be removed from core in favour of an extension?

**Comment by cjhenck** [comment]
@ronag Not really - HTTP is a full request-reply protocol, so your client could PATCH 2GB only to find out that the offset was incorrect.

**Comment by ronag** [comment]
@cjhenck: I don't follow. If the offset is incorrect then the server should reply with 409 without reading the full request.

**Comment by cjhenck** [comment]
@ronag Correct, but you cannot read the status reply on many HTTP clients without terminating the connection, so you do not know a reply has been received at all. The way around that is to terminate the connection after sending a response but then you sacrifice keep-alive and it may not work behind a load balancer.

**Comment by ronag** [comment]
@cjhenck: Interesting. Learned something new. Thanks!

**Comment by cjhenck** [comment]
You're welcome - I only know that because I encountered it working on a client for TUS :)

**Comment by ruv** [comment]
> you cannot read the status reply on many HTTP clients without terminating the connection

@cjhenck, does it mean that such clients don't support keep-alive? Could you please give some example?

**Comment by Acconut** [comment]
> @ronag With this HEAD would no longer be required and could be removed from core in favour of an extension?

No, the HEAD request still contains other information, including the length, metadata, expiration, checksums and whether it's a partial or final upload.

> @cjhenck You're welcome - I only know that because I encountered it working on a client for TUS :)

Me too, when we had to decide how a server should react if it fails to store a chunk while the client is still uploading data.

> @ruv does it mean that such clients don't support keep-alive?

These clients still support keep-alive but this mechanism not usable in these cases as the connection is terminated by the server.

**Comment by cjhenck** [comment]
> @ruv does it mean that such clients don't support keep-alive? 

I should clarify what I said here:

> @cjhenck Correct, but you cannot read the status reply on many HTTP clients without terminating the connection, so you do not know a reply has been received at all.

I suppose that this was not technically correct. On the client side, if you read the response it doesn't necessarily terminate the connection, it simply closes the upload stream that is part of the same request.  In my case I was working with the `HttpURLConnection` in Java as part of `tus-java-client` and had the same question, which @Acconut answered in detail with respect to the HTTP spec.  See https://github.com/tus/tus-java-client/issues/4.

**Comment by Acconut** [comment]
Closing in favor of #119. Please provide feedback there.
