### ISSUE TITLE
upload-type

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#103]
Read `upload-type` header in `POST` in order to specify the mime-type/content-type of the resource which will be uploaded.

**Comment by Acconut** [comment]
In order to keep the protocol at its core as small as possible we have refrained from adding a dedicated header from the upload's type to the specification. Instead, we encourage to use the `Upload-Metadata` header to apply arbitrary metadata to an upload which also may include its content type.
