### ISSUE TITLE
PATCH spec does not specify when upload-offset should be excluded

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#105]
PATCH spec does not specify that upload-offset should be excluded when the upload is complete?

**Comment by Acconut** [comment]
Yes, why should it? The `Upload-Offset` header can be used to determine that the upload is actually finished by checking whether it matches the `Upload-Length` header. If I am not understand your point, I would be pleased if you could explain it in more detail.

**Comment by ronag** [comment]
From the spec in `HEAD` it sounds like an upload is completed when `upload-offset` does not exists. It's a little bit inconsistent to have 2 conditions for completion:

```javascript
const complete = res.headers.get('upload-offset') === undefined || res.headers.get('upload-offset') === res.headers.get('upload-length')
```

**Comment by Acconut** [comment]
> From the spec in HEAD it sounds like an upload is completed when upload-offset does not exists. 

That's not correct. The HEAD request must always contain the `Upload-Offset` header and I think the specification stats this in a clear way:

> The Server **MUST always** include the Upload-Offset header in the response for a HEAD request, even if the offset is 0, or the upload is already considered completed.

Or did you have issues understanding this sentence? If so, we may be able to rephrase it.
