### ISSUE TITLE
POST should always include upload-offset

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#107]
Regardless if `creation-with-upload` is supported or not. Makes client code simpler?

**Comment by Acconut** [comment]
The offset of a newly created upload will always be 0, in particular if the Creation With Upload extension is not used. How would a client implementation benefit from this change?
The reason why the `Upload-Offset` header must be included, if the Creation With Upload extension is used, is that in this case the POST response must mimic the PATCH response where the header is required.
