### ISSUE TITLE
Why is checksum required for multiple small PATCH uploads?

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#108]

**Comment by Acconut** [comment]
Checksums are never required. They are an optional extension and may be used if the client desires to do. Therefore, I can't follow your question. Would you mind explaining your concerns?

**Comment by ronag** [comment]
> but MAY also use multiple small requests successively for scenarios where this is desirable, for example, if the Checksum extension is used.

This is confusing me a bit. It sounds like the checksum extension should be used for these scenarios.

**Comment by Acconut** [comment]
> This is confusing me a bit. It sounds like the checksum extension should be used for these scenarios.

The Checksum extension is one example for why one would choose to break the entire upload into multiple smaller requests instead of one single PATCH request as we usually recommend. This means that checksums are never required even if you use small requests.

**Comment by ronag** [comment]
@Acconut: Thanks! Might want to change the wording a little bit?

**Comment by Acconut** [comment]
Frankly, for me this sentence is quite clear, probably because I wrote it :) Would have any suggestions on what to improve there?

**Comment by ronag** [comment]
```
but MAY also use multiple small requests successively. This could be useful for scenarios where for example, the Checksum extension is used.
```

Just separate the sentence so that one does not directly associate small requests with checksums.
