### ISSUE TITLE
Upload-Defer-Length implicit?

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#111]
Why is it when no `upload-length` `Upload-Defer-Length` is not implicit? If it was then a tus server would be able to receive data from streaming non tus clients.

**Comment by Acconut** [comment]
We believe that explicitly deferring the upload length is superior. Imagine a situation where the `Upload-Length` header is not presented in the POST request. The server has no chance to know whether this was intentionally and the clients does not know the length yet or if it was just a mistake. Even worse, in later situation the client will have a hard time debugging the issue why the uploads are never finishing. Therefore you are required to explicitly include the `Upload-Defer-Length` header.

**Comment by Acconut** [comment]
> If it was then a tus server would be able to receive data from streaming non tus clients.

I don't think so you still need to include the `Tus-Resumable` header.
