### ISSUE TITLE
Paragraph numbers

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#113]
Please use paragraph numbers on the spec so we can easily refer to different sections.

**Comment by Acconut** [comment]
The problem with paragraph numbers is that you have to change many of them when you insert a new paragraph at somewhere else than at the end of a seciton. Therefore we decided to not use them. However, numbers will be added when the Markdown is transferred into a HTML file, see http://tus.io/protocols/resumable-upload.html.
