### ISSUE TITLE
Require ETag in POST and If-Match in PATCH requests

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#118]
In order to verify that the same resource is being uploaded. This is basically what the tus client does with local storage + fingerprint.

**Comment by Acconut** [comment]
Two things:

1. We are not able to require such a change without making it optional as this would introduce a breaking change. If we really want to implement this as being mandatory, it has to be postponed til tus 2.0 which is far from being in sight.

2. I am not exactly sure what the purpose is. Of course, it supplies another check that the client uploads to the same resource but this is already done using the upload URL. The client needs to be in knowledge of the correct upload URL which identifies the corresponding upload resource.

> This is basically what the tus client does with local storage + fingerprint.

I don't think this comparison is correct. The fingerprint is used to determine an upload URL from a given file. Furthermore, the client must be able to calculate this fingerprint only with information about the file itself. The ETag is generated by the server and therefore does not help the client by choosing a fingerprint.

Did I miss something from your proposal which would help me understanding your thoughts?
