### ISSUE TITLE
Resumable-download-protocol?

### ISSUE THREAD

**Issue by chrisdostert** [tus/tus-resumable-upload-protocol#122]
I've got an API that must support both the uploading and downloading of large files. 

Has there been any discussion about creating a resumable-download-protocol? Could build on those concepts already established by the resumable-upload-protocol.

**Comment by ronag** [comment]
The problem with resumable downloads is that the browser would need access to the filesystem. Which I believe is not possible due to security concerns.

**Comment by Acconut** [comment]
We had this discussion previously and came to the conclusion that tus (currently) focuses on providing a solution for upload and not download content. You can read more in a previous discussion, such as #74.

> @ronag: The problem with resumable downloads is that the browser would need access to the filesystem. Which I believe is not possible due to security concerns.

That would not be a real concern as the tus protocol is not limited to a browser environment.
