### ISSUE TITLE
Upload-Concat header: space after "final;" required?

### ISSUE THREAD

**Issue by acrispino** [tus/tus-resumable-upload-protocol#123]
Examples in the spec show no space after final;
```
POST /files HTTP/1.1
Upload-Concat: final;/files/a /files/b
```
```
HEAD /files/ab HTTP/1.1

HTTP/1.1 200 OK
Upload-Length: 11
Upload-Concat: final;/files/a /files/b
```

But the reference server [appears to expect a space](https://github.com/tus/tusd/blob/029191c8634c13989c81f0d8aa88d54dc4f997aa/unrouted_handler.go#L797). Are the examples incorrect or is the reference server incorrect?

**Comment by Acconut** [comment]
Thank you for bringing this up. The specification says that there must not be a space:

> In the case of a final upload, its value MUST be `final` followed by a semicolon and a space-separated list [...]

Therefore, the reference implementation was not fully correct but this has been addressed in https://github.com/tus/tusd/commit/7710fd79fb37290dd257325af640a87de049b87c.
