### ISSUE TITLE
Processing data after upload has finished

### ISSUE THREAD

**Issue by Enitoni** [tus/tus-resumable-upload-protocol#126]
I've implemented this protocol in my application, however I have a concern. My app allows uploading audio files, which will later be processed and uploaded to GCS. After the upload has finished, what is the best way to handle processing? Should I delete the database entry for the resumable upload, and start the processing job, or should I let the client initiate the processing job, multiple times?

I read your documentation but couldn't find anything useful on this. I feel like there should be more read on how to handle finished uploads.

**Comment by kvz** [comment]
At <https://transloadit.com> we use the post-create hooks to start the processing for our customers, I guess you could implement something similar? I'm afraid that apart from signalling that an upload is ready, further processing is a bit out of tus' scope.

**Comment by Acconut** [comment]
> Should I delete the database entry for the resumable upload, and start the processing job, or should I let the client initiate the processing job, multiple times?

This partly depends on your use case. We usually recommend to let the server initiate the processing after an upload is finished, as you mentioned. However, if you are in a situation where the exact same file may be upload/processed multiple times, it would be more efficient to upload it once and let the client initiate the processing multiple times.

Does this answer your question or would you like further assistance? :)

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
