### ISSUE TITLE
What does Tus mean? What is it's origin?

### ISSUE THREAD

**Issue by AndyOGo** [tus/tus-resumable-upload-protocol#128]
I'm curious of the name tus.
What is its definition, where does it originate from.
Or is it a pun?

**Comment by kvz** [comment]
In the beginning we were thinking along the lines of The Upload Server or Transloadit Upload Server but we finally decided that no, tus is a self contained name and not an acronym at all. Lowercase usage is preferred as an homage to unix

**Comment by AndyOGo** [comment]
@kvz 
Ahhh, thank you for your quick response.
That's very interesting and clarified the name for me.

May I ask you to add this somewhere as a footnote to the readme or official specs?

**Comment by kvz** [comment]
We could perhaps add it to the FAQ, but only if @Acconut agrees

**Comment by AndyOGo** [comment]
@kvz great idea:)

**Comment by Acconut** [comment]
> We could perhaps add it to the FAQ, but only if @Acconut agrees

Sounds good to me. I am happy to accept a PR for this :)
