### ISSUE TITLE
POST with content should be 400

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#129]
If performing POST with content-length the server should reply 400?

**Comment by Acconut** [comment]
Yes, 400 is a good status code in this case if the Content-Length is non-zero.

**Comment by ronag** [comment]
Related to https://github.com/tus/tus-resumable-upload-protocol/issues/104.

@Acconut: If I make a PR with updates in regards to failure modes will you have time to review and merge? Also, would that be interesting at all?

**Comment by Acconut** [comment]
Yes, that would be grad. Please incorporate those failure modes as non-mandatory suggestions so this is not a breaking change.

**Comment by Acconut** [comment]
Closing this since #88 will allow POST requests with content.
