### ISSUE TITLE
Upload-Defer-Length HEAD

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#132]
The spec says that a HEAD response MUST contain `upload-length`. However, how should we handle the `Upload-Defer-Length` case where the `upload-length` is not yet known?

**Comment by Acconut** [comment]
That's not correct. The specification requires the header if the size is defined:

> If the size of the upload is known, the Server MUST include the Upload-Length header in the response.

**Comment by ronag** [comment]
Yep, sorry, noticed that afterwards.

**Comment by Acconut** [comment]
No worries, I just wanted to clarify that for other visiting this issue.
