### ISSUE TITLE
Unable to resume uploads, Upload-Offset is always 0

### ISSUE THREAD

**Issue by vldgeorgiev** [tus/tus-resumable-upload-protocol#140]
Hi
There is one problem I am having while making a pascal client for tus.
I can successfully issue a POST to create a resource. It returns the resource location URL, which I checked and it returns a header "Upload-Offset:0". This is expected, because no data has been uploaded yet.

After that I send a PATCH and it starts uploading.  If I interrupt the connection before it is finished, the HEAD call for the resource still returns "Upload-Offset:0", so no data has been saved and the upload can't be resumed. If I understand the protocol correctly, the offset should indicate the number of bytes that were transferred before the interruption.
If the connection is not interrupted, the upload finished properly and the Upload-Offset indicates the size of the upload.

I made several tests: with my client and with the Postman app, on the https://master.tus.io server and on a server running the official node.js implementation. All the results were the same.

The only conclusion that comes to mind is that I am not using chunked transfer mode. Is that a requirement for resuming?

Here is the Postman PATCH request, for reference
```
PATCH /uploads/e8395bfb60b88618e50b1948eed5149e HTTP/1.1
Host: XYZ
Tus-Resumable: 1.0.0
Content-Type: application/offset+octet-stream
Upload-Offset: 0
Content-Length: 10000000
Cache-Control: no-cache
```

> The tus protocol is built upon the principles of simple pausing and resuming. In order to pause an upload you are allowed to end the current open request. The Server will store the uploaded data as long as no violations against other constraints (e.g. checksums) or internal errors occur. 

There are no checksums sent and I don't think a simple disconnect would cause internal server errors.

Thanks for any advice on the topic.

**Comment by vldgeorgiev** [comment]
Yes, I got that. Thanks.
From reading the docs I had the impression that they are talking about HTTP Chunked transfer mode, which is a different thing. While they actually meant issuing independent PATCH requests.

**Comment by Acconut** [comment]
> @ronag You need to upload in chunks. The upload-offset is relative to the last successful PATCH.

This is not correct. Even if a PATCH request fails, the server is expected to store as much data of the request as possible. We do not recommend splitting an upload into multiple HTTP PATCH requests as this adds an overhead and is in 99% of the use cases not necessary.

> @vldgeorgiev After that I send a PATCH and it starts uploading. If I interrupt the connection before it is finished, the HEAD call for the resource still returns "Upload-Offset:0", so no data has been saved and the upload can't be resumed. If I understand the protocol correctly, the offset should indicate the number of bytes that were transferred before the interruption.

That's correct.

> I made several tests: with my client and with the Postman app, on the https://master.tus.io server and on a server running the official node.js implementation. All the results were the same.

We currently have an issue with master.tus.io where a PATCH request is not stored properly if it's small than 5MB. I hope to have this resolved in the next days but in the meantime you might want to test your client against a local instance of [tusd](https://github.com/tus/tusd). This server is guaranteed to properly store every single byte is receives.

> The only conclusion that comes to mind is that I am not using chunked transfer mode. Is that a requirement for resuming?

No, the HTTP chunked transfers are not necessary for tus to work properly.

**Comment by bluetianx** [comment]
@vldgeorgiev  if do you find client of C# , there is a client [github](https://github.com/bluetianx/BirdMessenger)

**Comment by vldgeorgiev** [comment]
@bluetianx Thanks. I am not using a C# client, but I just had a look at the implementations at https://tus.io/implementations.html, to see what they do.

**Comment by Acconut** [comment]
> Btw, I looked at the code of the C# or the Java client reference implements and either one or both of them were doing the same.

Yes, the Java client does it because it has to account for memory-constrained Android devices. You can find more details here: https://github.com/tus/tus-java-client/blob/master/src/main/java/io/tus/java/client/TusUploader.java#L125-L129. If you don't have a good reason, you probably shouldn't segment your upload into multiple PATCH requests :)

> With the default tusd -dir ./data it runs, but it doesn't accept POST creation requests, and I can't make a PATCH without the resource URL

This command is correct. You can then send your POST requests to `http://localhost:1080/files/`. Any other URL will not accept a POST request.

> Btw, doesn't master.tus.io run the same tusd?

Yes, master.tus.io uses tusd but the uploads are stored on AWS S3 and not on disk. We sometimes switch the storage backend to test our latest features before we put them into production. So, although it should not happen, we sometimes have issues with master.tus.io since it's our test field.

**Comment by vldgeorgiev** [comment]
My only reason to go with multi patches was that I could not make it store interrupted uploads in the two servers :)
@Acconut  Now that I tested a localhost tusd server, it works and saves any arbitrary number of bytes, no matter when the connection is interrupted. So I might revert back to a single PATCH as it was initially.

But can you confirm if the node.js server at https://github.com/tus/tus-node-server also stores a partial interrupted request like tusd?
Because in the test with the instance on our servers it also didn't store data unless the PATCH was complete. Could be a problem with our configuration of course.

**Comment by Acconut** [comment]
> Now that I tested a localhost tusd server, it works and saves any arbitrary number of bytes, no matter when the connection is interrupted. So I might revert back to a single PATCH as it was initially.

I am happy to hear that :)

> But can you confirm if the node.js server at https://github.com/tus/tus-node-server also stores a partial interrupted request like tusd?

No, I sadly can't confirm this. tus-node-server is not in good condition and at least its GCSStore and S3Store have major issues. I would not recommend you to use it right now for serious purposes.

**Comment by Acconut** [comment]
> @Acconut: We currently have an issue with master.tus.io where a PATCH request is not stored properly if it's small than 5MB. I hope to have this resolved in the next days but in the meantime you might want to test your client against a local instance of tusd. This server is guaranteed to properly store every single byte is receives.

BTW, the problems with master.tus.io, which I mentioned in a comment above, have just been fixed. So you can test against master.tus.io again without problems.

**Comment by vldgeorgiev** [comment]
master.tus.io is also working now.
Thanks :)
