### ISSUE TITLE
POST 409 response should include upload-offset header

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#142]
POST 409 response should include upload-offset header.

That way you don't have to first do a HEAD check for 404 and then create the resource.

**Comment by Acconut** [comment]
I don't understand what you are trying to say. A POST request (for creating an upload) never returns the 409 Conflict status code. Are you referring to the PATCH request?

**Comment by ronag** [comment]
A POST request MAY include an id (i.e. I want to create a resource with this id). If it already exists the server SHOULD reply with 409.

**Comment by bluetianx** [comment]
tus will create unique identification for every post request, then it do not need 409 in response

**Comment by ronag** [comment]
> tus will create unique identification for every post request, then it do not need 409 in response

Sure, what is the response if a resource id is passed? 400 always?

**Comment by bluetianx** [comment]
you will get a new unique identification in reponse , tus do not care resource id .you should save record that correlation between unique identification in response of post request and upload flle in client,if You don't want to upload the same file over and over again

**Comment by Acconut** [comment]
> It's a bit weird, since a resource id is sometimes allowed in POST requests.

As @bluetianx correctly said, the tus *specification* does not allow a resource id in POST requests. However, if a tus *implementation* still allows and respects a resource id, then this behavior is non-standard. I am not aware of any such implementation but they may exist. FYI, the official reference implementation tusd (https://github.com/tus/tusd) does not allow you to specify a resource id and will return a 405 Method Not Allowed if you try to.

**Comment by ronag** [comment]
Fair enough!
