### ISSUE TITLE
C++ client library

### ISSUE THREAD

**Issue by EhsanVahab** [tus/tus-resumable-upload-protocol#144]
Hello friends,
is there any c++ or c client library to upload the files?

**Comment by Acconut** [comment]
Unfortunately, to my knowledge there is not tus client library written in C/C++. However, if you want to build one on your own, we're happy to assist you!

**Comment by i-mighty** [comment]
Hi any new information on this?

**Comment by smatsson** [comment]
Can this repo be usable? https://github.com/clarkhillm/TUSQTClinet
