### ISSUE TITLE
DotNET client implementation

### ISSUE THREAD

**Issue by bluetianx** [tus/tus-resumable-upload-protocol#145]
I have a project that DotNET(C#) client implementation under MIT LICENSEI ，[github](https://github.com/bluetianx/BirdMessenger)

**Comment by Acconut** [comment]
Thank you very much! I added it to our list over at https://tus.io/implementations.html

**Comment by bluetianx** [comment]
thanks I am very glad to receive your reply

**Comment by bluetianx** [comment]
> Thank you very much! I added it to our list over at https://tus.io/implementations.html

thanks I am very glad to receive your reply @Acconut
