### ISSUE TITLE
Standardization process for TUS

### ISSUE THREAD

**Issue by ioggstream** [tus/tus-resumable-upload-protocol#168]
## Question

Is there a standardization process for tus.io?
It would be great to discuss the spec inside the IETF.

**Comment by Acconut** [comment]
FYI, moved this issue into the more appropriate repository.

**Comment by ioggstream** [comment]
Hi @Acconut, we've recently launched a new IETF workgroup for standardizing HTTP API Building Blocks. The mailing list is here https://www.ietf.org/mailman/listinfo/httpapi You're welcome to join and present us TUS :)

**Comment by Acconut** [comment]
@ioggstream Thank you for invitation and apologies for my late reply! I would love to check it out but could you briefly explain what the working group is about (or provide some links with more details about your efforts)? That would help a lot :)

**Comment by ioggstream** [comment]
The workgroup charter is here https://datatracker.ietf.org/wg/httpapi/about/

> Its output can include the following:
> • Specifications for HTTP extensions that relate to HTTP APIs (typically, new HTTP header and/or trailer fields)
> • Specifications for new message body formats, or conventions for their use in HTTP APIs (e.g., patterns of JSON objects)
> • Best practices and other documentation for HTTP API designers, consumers, implementers, operators, etc.

**Comment by Acconut** [comment]
Thank you for helping to initialize this, @ioggstream! Resumable uploads are being discussed in the HTTP WG since some time now: https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/

**Comment by ioggstream** [comment]
Thanks!
