### ISSUE TITLE
Request: Swagger / OpenAPI documentation of the API

### ISSUE THREAD

**Issue by RubenGarcia** [tus/tus-resumable-upload-protocol#169]
I could not find any swagger or OpenAPI documentation of the tus protocol. This would be useful, e.g., when creating proxies with go-swagger.
Is there unpublished OpenAPI documentation which could be added to this project?

**Comment by Acconut** [comment]
Interesting idea! We don't have an OpenAPI document but would be happy to accept one if you want to contribute.

**Comment by RubenGarcia** [comment]
I'll try to make one when I can.

**Comment by Acconut** [comment]
Great! Let me know if you have any questions

**Comment by RubenGarcia** [comment]
First draft.

[swagger-openapi2.yaml.txt](https://github.com/tus/tus-resumable-upload-protocol/files/5304070/swagger-openapi2.yaml.txt)
[openapi3.yaml.txt](https://github.com/tus/tus-resumable-upload-protocol/files/5304071/openapi3.yaml.txt)

**Comment by RubenGarcia** [comment]
I have not heard any updates regarding this in a while. Did you have problems setting up cicd?

**Comment by Acconut** [comment]
I am sorry, @RubenGarcia, I lost track of this discussion. We haven't yet tried to set up the CI for OpenAPI. I explained some more details in https://github.com/tus/tus-resumable-upload-protocol/pull/170#issuecomment-761906862.

**Comment by RubenGarcia** [comment]
The last comment on #170 seem to indicate that CI is now working, so this can be closed.

**Comment by Acconut** [comment]
Good catch! Thanks for closing the issue!
