### ISSUE TITLE
Byte-range support for iOS compatibility

### ISSUE THREAD

**Issue by beevelop** [tus/tus-resumable-upload-protocol#171]
There were already a few discussions about supporting Byte-range (content-range / partial-range) a few years ago. For now, `tus` and `tusd` don't implement support for it, which is understandable in the respective context:
- https://github.com/tus/tus-resumable-upload-protocol/issues/2: "Range" vs. "Content-Range"
- https://github.com/tus/tus-resumable-upload-protocol/issues/116: Upload-Offset vs Range?
- https://github.com/tus/tusd/issues/296: Upload to tusd behind HTTPS reverse proxy disconnects with EOF

The decision to not support Byte-range leads to another nasty side-effect on our "favourite" mobile operating system _iOS_: **Media files (audio / video) stored on `tus` can not be played on iOS!**

> HTTP servers hosting media files for iOS must support byte-range requests, which iOS uses to perform random access in media playback. (Byte-range support is also known as content-range or partial-range support.) Most, but not all, HTTP 1.1 servers already support byte-range requests.

This renders `tus` unusable for e.g. storing video / audio notes through a mobile app and enabling the user to play the respective files **without** downloading them in advance.

**Comment by smatsson** [comment]
Hi,

This seems unrelated to this repository as tus is a protocol for file uploads and you are asking for are headers related to downloading files which is out of scope for the protocol. 

I think your chances are better at getting a response if asked in the specific server implementation being used (e.g. https://github.com/tus/tusd).

**Comment by beevelop** [comment]
Thank you @smatsson for the heads-up. I close this one in reference to https://github.com/tus/tusd/issues/432 :+1:
