### ISSUE TITLE
Protocol version confusion

### ISSUE THREAD

**Issue by tedidim19** [tus/tus-resumable-upload-protocol#189]
Hello everybody,

Upon implementing the TUS protocol in our API, we ran into this version: https://www.ietf.org/archive/id/draft-tus-httpbis-resumable-uploads-protocol-00.html#name-authors-addresses and there has been a bit of a confusion what is this protocol, are they related, etc?

Thank you in advance for you response!

**Comment by smatsson** [comment]
Hi! 

The protocol you are linking to is the next version of the tus spec. We are working with the IETF to make this a http standard. The latest version of the IETF draft spec can be [found here](https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/) and it explains the difference pretty well: 

>   The tus v1 protocol (https://tus.io/) is a specification for a
>    resumable file upload protocol over HTTP.  It inspired the early
>    design of this protocol.  Members of the tus community helped
>    significantly in the process of bringing this work to the IETF.

Hope it clears it up!

**Comment by Acconut** [comment]
There is also this blog post now, which helps understand the relationship between the two protocols: https://tus.io/blog/2023/08/09/resumable-uploads-ietf In a nutshell: the work from the IETF is the part from tus we are trying to standardize.
