### ISSUE TITLE
Which StatusCode of response must server return, if server want to indicate a success HEAD request

### ISSUE THREAD

**Issue by bluetianx** [tus/tus-resumable-upload-protocol#192]
Which StatusCode of response must server return, if server want to indicate a success HEAD request ?
Server must return 200 statusCode ?

TusVersion : 1.0.0

**Comment by Acconut** [comment]
That depends on the request type. PATCH requests must get a 204, POST a 201, and for HEAD no specific response is required, but a 200 or 204 is usually the best.

**Comment by bluetianx** [comment]
OK, Thank you for your reply, 

> That depends on the request type

Sorry, I forgot to express which Request Type, I want to ask about HEAD request Type.


>  for HEAD no specific response is required, but a 200 or 204 is usually the best.

OK, I understand, but I think Tus should indicate a  success statusCode

**Comment by Acconut** [comment]
I agree. We should add a recommendation to respond with 200 or 204.

**Comment by bluetianx** [comment]
> We should add a recommendation to respond with 200 or 204.

Can I update the Protocol file with PR ?

**Comment by Acconut** [comment]
Thank you for the offer, but I also added a brief text in ab284dc093b5a2d88f5de3618891309bbf5e1b6c and 61083ff6c3bad78ca51aa9e4e8e054b91563be63.
