### ISSUE TITLE
How Can I learn about Tus V2?

### ISSUE THREAD

**Issue by bluetianx** [tus/tus-resumable-upload-protocol#193]
Hi , all
 I heard that The tus V2 has been finished, But I can not find content about v2, because I would like to implement it.

**Comment by smatsson** [comment]
Hi,

The tus v2 spec has been renamed to `Resumable Uploads For Http` and is currently being adopted by the IETF.

Draft spec: https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/
Related issues: https://github.com/httpwg/http-extensions/issues?q=is%3Aissue+is%3Aopen+label%3Aresumable-upload

**Comment by Acconut** [comment]
Adding to @smatsson's comment, please don't confuse tus (the protocol) and tusd (the Go server implementation). We release tusd v2 not too long ago (https://tus.io/blog/2023/09/20/tusd-200), but tus v2 is not finished yet.

**Comment by bluetianx** [comment]
ok
Thank you, I will learn about that first @smatsson @Acconut
