### ISSUE TITLE
Upload-Metadata could be Structured Field Values (RFC 8941)

### ISSUE THREAD

**Issue by mitar** [tus/tus-resumable-upload-protocol#195]
There is now great spec for Structured Field Values: https://www.rfc-editor.org/rfc/rfc8941.html

I would suggest that in future iterations of the protocol, Upload-Metadata is provided using that format, instead of having a custom way to specify metadata. (You get some basic typing information and they handle various types of values.)

**Comment by Acconut** [comment]
Thanks for the pointer! This is already on our radar and the next version of tus will be based on https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/, which we contribute to and which also uses structured fields :)

**Comment by mitar** [comment]
I was reading that spec but there was no metadata mentioned except for Content-Type and Content-Disposition header fields, nor direct mention of the extra Upload-Metadata or similar. So my assumption was that general metadata was dropped from the spec?

**Comment by Acconut** [comment]
The IETF draft focuses on the core uploading part, meaning optional stuff like metadata, expiration, concatenation are left out on purpose. HTTP extension like this should be composable, so metadata does not fit in there well.

Our plan is that once the resumable upload draft is completed in its current scope, we can built tus 2.0 on top of it and add additional extensions like metadata and expiration. You can read more about this in-depth at https://tus.io/blog/2023/08/09/resumable-uploads-ietf.
