### ISSUE TITLE
Support zero length uploads

### ISSUE THREAD

**Issue by bluetianx** [tus/tus-resumable-upload-protocol#196]
if UploadLength is set to zero without setting IsUploadDeferLength to true,  is this case reasonable in Creation of Protocol Extensions?  I do not  find  detail about that

**Comment by Acconut** [comment]
Yes, Upload-Length can be 0. The spec only requires the header to be non-negative, so 0 is explicitly included.

> The Upload-Length request and response header indicates the size of the entire upload in bytes. The value MUST be a non-negative integer.

**Comment by bluetianx** [comment]
> The spec only requires the header to be non-negative 

I can not find it in Creation of Protocol Extensions, but I can see it in Patch Protocol. Shall fill it in Creation of Protocol Extensions?

**Comment by Acconut** [comment]
> I can not find it in Creation of Protocol Extensions, but I can see it in Patch Protocol. Shall we fill it in Creation of Protocol Extensions?

We can add a statement to explain that zero-length uploads are explicitly allowed, yes.
