### ISSUE TITLE
Response to HEAD should use Content-Length, not Offset

### ISSUE THREAD

**Issue by jonhoo** [tus/tus-resumable-upload-protocol#26]
The protocol dictates that the response to a HEAD request on an incomplete upload should reply with an Offset header indicating how much data the server already has. Wouldn't it make more sense to use the Content-Length header here, as we are really telling the client how much data is already stored on the server?

**Comment by Acconut** [comment]
Some final notes:

* We stick with Offset instead of Content-Length
* GET requests/responses is not defined by tus core or any extension
* Streaming downloads are not contained in the specification either.
