### ISSUE TITLE
Define behaviour when uploading non-contiguous chunks 

### ISSUE THREAD

**Issue by sandfox** [tus/tus-resumable-upload-protocol#3]
As per IRC convo:

Should the server accept uploading of non-contiguous chunks?
For example client uploads ranges [0-100], then [240-360] then [400-420]. Do we accept this happily or throw toys out of the pram?

If acceptable behaviour, how should results of such be displayed when making a `HEAD` request?

with contiguous blocks `Range: bytes=0-100`
with non-contigous blocks `Range: bytes=0-100,240-360,400-420` ?? _no idea if this is sane or not_

**Comment by Acconut** [comment]
The last thing needed to finish this extension is that the header `Offset` header must contain multiple offsets.

```
Offset: 100-199,300-399
```

In this example (assume the file has a size of 400 bytes) the first 100 bytes (0-99) and the third 100 bytes (200-299) are already uploaded. Offsets in these ranges won't be allowed in 1.0 (see #51). The bytes in the ranges 100-199 and 300-399 aren't set yet and offsets between these values or them itself are accepted, e.g. 150, 300 and 199.

If the final size of the upload is not known (see #16) the end of the range should be omitted, e.g.:

```
Offset: 100-199,300-
```

Offsets between 100 and 199 are allowed and everything greater or equal than 300.

**Comment by Acconut** [comment]
Merge extension merged in #56.
