### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ChristianUlbrich** [tus/tus-resumable-upload-protocol#33]
We have adopted the semantics of the protocol in one of our applications. What is the current status of the project? Are there any plans on updating / enhancing the protocol (e.g. checksums)? It seems, that the development has somewhat stalled. If not, what is the best way to contribute to the project? Reporting/discussing in issues or PR or both?

**Comment by kvz** [comment]
Working on a blog post with Project Status that we'll publish soon.
