### ISSUE TITLE
Where to specify filename

### ISSUE THREAD

**Issue by MarkMurphy** [tus/tus-resumable-upload-protocol#38]
The protocol implementations I've seen store the chunked data in a .bin file. No where in the protocol does it mention how a client should provide a target file name to move the upload to once complete. 

Video and audio files, among others no longer work/are recognized when they've been renamed from something like `my_video.mp4` to `036f1378006746bcb40a0e3981257552.bin`. Has the protocol left this out for a reason?

**Comment by Acconut** [comment]
When 1.0 will be release the metadata extension should be used for this task.

**Comment by kvz** [comment]
@MarkMurphy just to clarify

> If the metadata is kept out of the body then that would leave the protocol free to use whatever method it wants: stick with the current implementation or go with what I suggested above.

This is what's happening in 1.0 now : )
