### ISSUE TITLE
Is the `reason` of response from tus server must match the protocol?

### ISSUE THREAD

**Issue by FuGangqiang** [tus/tus-resumable-upload-protocol#69]
of course the `status code` must be the same to the protocol,
but what about the `reason` part? 

Is it also must same to the protocol?

**Comment by Acconut** [comment]
The specification defined status codes plus the reason, e.g. `200 OK`. While client implementations checking for the reason are rare, we recommend to use the standardized reasons. Especially since HTTP/2 does not support reasons any more, see http://evertpot.com/http-2-finalized/.

**Comment by FuGangqiang** [comment]
thanks for the reply.

**Comment by Acconut** [comment]
No problem :)
