### ISSUE TITLE
how to response HEAD method when supporting concatenation-unfinished extention?

### ISSUE THREAD

**Issue by FuGangqiang** [tus/tus-resumable-upload-protocol#73]
when server supports `tus-defer-length` and `concatenation-unfinished` , 
the upload-length is unknown, Is the response like this?

```
HEAD /files/ab HTTP/1.1

HTTP/1.1 200 OK
Upload-Defer-Length: 1
Upload-Concat: final;/files/a /files/b
```

when all the parts length are known, but upload is not finished,
should it to response with a header to indicate that it is not finished?
or upload-offset header?

**Comment by Acconut** [comment]
> Is the response like this?

Yes.

> when all the parts length are known, but upload is not finished,
should it to response with a header to indicate that it is not finished?
or upload-offset header?

The specification of the Concatenation extension does indeed define these cases:

> The response to a HEAD request SHOULD NOT contain the Upload-Offset header unless the concatenation has been successfully finished. After successful concatenation, the Upload-Offset and Upload-Length MUST be set and their values MUST be equal.
> [...]
> The Upload-Length header MUST be included if the length of the final resource can be calculated at the time of the request. 

Basically, in your case the `Upload-Length` header must be presented but the `Upload-Offset` header must be omitted.
