### ISSUE TITLE
1.0 Launch todos

### ISSUE THREAD

**Issue by kvz** [tus/tus-resumable-upload-protocol#76]
We're thinking what is required before we launch 1.0, and are putting all todos in this page. 

Are we missing anything? Please feel free to add.

## Before 1.0 Launch

 - [x] tusd: Switch to X-HTTP-Method-Override (@acconut)
 - [x] tus-java-client: Switch to X-HTTP-Method-Override (@acconut)
 - [x] protocol: Go over each issue in https://github.com/tus/tus-resumable-upload-protocol/issues, and either close it, or label it 2.0 (@acconut)
 - [x] blog: Finish technical launch post for tus.io blog (@kvz, @ajvanloon)
 - [x] meta: Seek interested news outlets who want coverage (@kvz)
 - [x] website: Add a smaller 'Who uses tus' section on the homepage with the bigger companies and offer people a direct PR link. (@kvz)
 - [x] tusd-infra: Use latest version of tusd and not precompiled one via `wget "$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/tus/tusd/releases/latest | sed 's/tag/download/')/tusd_linux_amd64.tar.gz"`` (@kvz)
 - [ ] tus-java-client: Push to Maven Central (@acconut)
 - [x] website: Make sure the demo is functioning properly - @hedgerh had problems in chrome last week (@acconut)
 - [x] website: Go over website’s copy again and check for spelling errors, wording, and markdown violations (possibly automated) (@ajvanloon, @kvz)
 - [x] blog: Finish press release post for transloadit.com blog (@kvz, @ajvanloon)
 - [ ] meta: Discuss possibility of an early announcement by Vimeo (@vayam)

## 1.0 Launch!

 - [x] meta: Sync with news outlets (@kvz)
 - [x] tus: Merge 1.0 into master (@acconut)
 - [x] blog: Publish the launch posts on tus.io & transloadit.com (@kvz)
 - [x] meta: post on HackerNews, link to blog post (@kvz)
 - [x] blog: Update blogpost with HackerNews link for comments (@kvz)
 - [x] meta: Update Transloadit's & tus' twitter/linkedin/fb post on reddit/slashdot (@kvz)
 - [x] meta: Get email subscribers and mail them the blogpost & hacker news link for comments (with intercom?) (@acconut, @kvz)
 - [x] meta: Reach out to Peter Cooper, pointing to the blog post and a tweet to RT with his publications (@kvz)
 - [x] meta: Reach out to Olaf van Miltenburg from Tweakers.net, pointing to the blog post, the tech.eu post, the press release, and the earlier tweaker.net coverage (@kvz)
 - [x] meta: Email press release to all tech editors, pointing to the blog post (@kvz)

## After 1.0 Launch

 - [ ] protocol: Finish Developer Guide
 - [ ] protocol: RAML spec
 - [ ] client: Implementation tester

**Comment by Acconut** [comment]
Closing this as the 1.0 launch has happend long ago, even if some of the item on the lists haven't been done yet. Some people report that they were confused about tus' current status.
