### ISSUE TITLE
Upload-Length Entity-Length Upload-Offset Offset

### ISSUE THREAD

**Issue by choonkeat** [tus/tus-resumable-upload-protocol#77]
Seeing that all the projects are as recently updated, I'm wondering what are the correct headers?

https://github.com/tus/tusd/commit/46fabad3 says one thing https://github.com/tus/tus-js-client, https://github.com/tus/TUSKit, https://github.com/tus/tus-java-client seem to follow but i didn't check if *all* the headers matches

http://tus.io/protocols/resumable-upload.html seem to talk about `Entity-Length` and `Offset` and then there's also `Tus-` prefixed headers (vs the `Upload-` prefixed headers)

Thanks

**Comment by kvz** [comment]
Hi, some more on the projects' status in this post: http://tus.io/blog/2015/09/19/project-status/

Which also refers to the 1.0 pull request that has the full 1.0 protocol proposal here: https://github.com/tus/tus-resumable-upload-protocol/blob/1.0/protocol.md

I think that will clarify : ) If not, please let me know.

We're pretty [close](https://github.com/tus/tus-resumable-upload-protocol/issues/76) to launching 1.0, that will hoepfully make things less confusing.

**Comment by choonkeat** [comment]
> I think that will clarify : ) If not, please let me know.

Got it, so https://github.com/tus/tus-resumable-upload-protocol/blob/1.0/protocol.md#headers is correct. Headers are `Upload-*` and `Tus-*`
