### ISSUE TITLE
Concatenation extension has ambiguous behavior

### ISSUE THREAD

**Issue by cjhenck** [tus/tus-resumable-upload-protocol#81]
The concatenation extension seems to leave unclear the following questions:

- Does a HEAD request for the partial uploads include an offset?  The reference implementation does, but it is stated that a HEAD request must not return an offset.
- Does the HEAD request include Upload-Length for the partial uploads?  

I think the answer to both of these is yes based on the reference implementation, but the protocol does not make a distinction between the partial and final uploads on those points.

**Comment by cjhenck** [comment]
Looking at the reference implementation, it seems like those two statements apply to

**Comment by Acconut** [comment]
Closing, since the corresponding PR #85 has been merged in 3326720a379118f20cd91e12bb8a0fe79658dbf6. Thank you for this contribution.
