### ISSUE TITLE
Allow setting of alternate download url

### ISSUE THREAD

**Issue by mhiemstrapodiumtv** [tus/tus-resumable-upload-protocol#87]
I am using the tus.io javascript client. That means that the tus server url is located in my Javascript. This means users know the upload url. This also means they know the download url and when using a random generator can guess download urls. Is there a way to prevent downloading from tus (So I can create my own download system that streams the file directly from the harddisk through a servlet e.g) or is it possible to create a tus setting to supply a alternate download url, that replaces the current download url, so people have a hard time downloading from the tus server.

**Comment by Acconut** [comment]
There is an integral part about tus and downloading, in general, which you seem to misunderstand:
The tus *specification* does not make any assumptions about how content of uploads can or will be moved at any point of time. Therefore, in the eye of the protocol itself, there does not exist a thing such as the "download URL". We did not make this choice to upset users but instead to allow us and the entire community to focus on one point and one point only: Uploading.

From the specification's view, we cannot provide you with an answer. However, most server *implementations* (including the official ones) have the ability to download the content of uploads for the sake of testing and simplicity of integration. Therefore, you may want to disable this functionality in your tus server but it's out of the specification's scope.

I may be able to help you with it if you can tell me which tus server software you are using.
