### ISSUE TITLE
PATCH creation

### ISSUE THREAD

**Issue by ronag** [tus/tus-resumable-upload-protocol#98]
We are almost able to support the tus protocol. However, since we generate a unique id on client side we do not want to create an upload resource using a POST call. Since several clients might start uploading (creating) the same id, which in our case should be allowed.

Could sending PATCH to a resource that does not yet exist, create it? I think this aligns with the HTTP specification and the tus protocol does not seem to either allow or disallow it?

https://tools.ietf.org/html/rfc5789
```
§2 ... If the Request-URI does not
   point to an existing resource, the server MAY create a new resource,
   depending on the patch document type (whether it can logically modify
   a null resource) and permissions, etc. ...
```

**Comment by ronag** [comment]
This is how our uploads works:

```javscript
async function upload (file) {
  const tag = hash({
    name: file.name.toLowerCase()
    size: file.size,
    lastModified: file.lastModified
  })
  const id = `${tag}.${file.name.split('.').pop().toLowerCase()}`
  
  let res = await window.fetch(`file/${id}?timeout=200`, { method: 'HEAD' })
  let position = parseInt(res.headers.get('upload-offset'), 10) || 0

  while (position < file.size) {
    res = await window
      .fetch(`file/${id}`, {
        method: 'PATCH',
        headers: {
          'upload-offset': position,
          'upload-length': file.size,
          'upload-type': file.type,
          'upload-expires': new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toUTCString(),
          'content-type': 'application/offset+octet-stream'
        },
        body: file.slice(position, position + 128e6)
      })
    if (res.status === 204) {
      position = parseInt(res.headers.get('upload-offset'), 10)
    } else {
      throw res
    }
  }
}
```

**Comment by Acconut** [comment]
> However, since we generate a unique id on client side we do not want to create an upload resource using a POST call.

Do you mind explaining why you decided to create the upload URL on the client side?

Did you have a look at the upcoming Creation With Upload extension (see https://github.com/tus/tus-resumable-upload-protocol/pull/88)? It adds a way to provide a part of the file in the initial `POST` request which seems very similar to what you are trying to achieve here, from my point of view.

**Comment by ronag** [comment]
@Acconut: See my comment in https://github.com/tus/tus-resumable-upload-protocol/pull/99
